openapi: 3.0.0
info:
  title: Test
  version: v1
paths:
  /test:
    get:
      operationId: get
      responses:
        '200':
          description: Get
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/A'
                  - $ref: '#/components/schemas/B'
components:
  schemas:
    User:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
        password:
          type: string
        createdAt:
          type: integer
    Training:
      type: object
      properties:
        overallRating:
          type: string
        trainingLevel:
          type: string
        description:
          type: string
        title:
          type: string
        imageUrl:
          type: string
        createdBy:
          $ref: "#/components/schemas/User"
    Rating:
      type: object
      properties:
        title:
          type: object
        stars:
          type: object
        createdBy:
          $ref: "#/components/schemas/User"
        training:
          $ref: "#/components/schemas/Training"