version: '3.8'

services: 
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  # security-wrapper:
  #   image: trainwithme-auth-server
  #   build: auth-server/
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
volumes:
  postgres-data:
networks:
  defaultNetwork: