# Generated by Django 4.1.6 on 2023-02-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('added_by', models.CharField(max_length=20)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('exercises', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('AV', 'ADVANCED'), ('MD', 'MEDIUM'), ('ES', 'EASY'), ('TD', 'TODDLER')], default='MD', max_length=2)),
                ('exercise_type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='data_app.exercisetype')),
            ],
        ),
    ]
