# Generated by Django 4.1.6 on 2023-02-04 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExerciseType',
            new_name='TrainingType',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='exercise_type',
            new_name='training_type',
        ),
    ]
