# Generated by Django 4.1.6 on 2023-02-04 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0002_rename_exercisetype_trainingtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_app.trainingtype'),
        ),
    ]
