# Generated by Django 4.1.6 on 2023-02-04 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0003_alter_training_training_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_type',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.PROTECT, to='data_app.trainingtype'),
            preserve_default=False,
        ),
    ]
